esphome:
  name: air-quality-monitor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air-Quality-Monitor"
    password: !secret fallback_ssid_password

captive_portal:
    
i2c:
  - id: bus_a
    sda: GPIO2  #D4
    scl: GPIO0  #D3
    scan: true

uart:
  - id: uart_bus1
    tx_pin: GPIO1 #D10
    rx_pin: GPIO3 #D9
    baud_rate: 9600
  - id: uart_bus2
    tx_pin: GPIO15  #D8
    rx_pin: GPIO13  #D7
    baud_rate: 9600

sensor:
  - platform: htu21d
    i2c_id: bus_a
    address: 0x40
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 10s
  
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_bus1
    pm_1_0:
      name: "PM1.0"
      device_class: "pm1"
    pm_2_5:
      name: "PM2.5"
      device_class: "pm25"
    pm_10_0:
      name: "PM10.0"
      device_class: "pm10"
    update_interval: 30s
    
  - platform: mhz19
    uart_id: uart_bus2
    co2:
      name: "MH-Z19 CO2"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 10s
    automatic_baseline_calibration: false

switch:
  - platform: gpio
    pin:
      number: GPIO12  #D6 PMS5003的Pin3为set，接至D6
    id: pms_set
    name: "颗粒物采集"

interval:
  - interval: 120s
    then:
      - switch.turn_on: pms_set
      - delay: 20s
      - switch.turn_off: pms_set
